name: Deploy Backend
on:
  push:
    branches:
      - master
      - development
    paths:
      - 'api/**'
  pull_request:
    branches:
      - master
      - development
    types: [closed]
    paths:
      - 'api/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'development'
        type: string

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref == 'refs/heads/master' && 'production' || 'staging') }}
    
    env:
      ENVIRONMENT_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref == 'refs/heads/master' && 'production' || 'staging') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
    
    - name: Configure backend settings
      env:
        RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET_KEY }}
      run: |
        echo "🔧 Configuring backend for ${{ env.ENVIRONMENT_NAME }} environment"
        
        # Create backup
        cp api/config.php api/config.php.backup
        
        # Debug: Check if secret is available
        if [ -z "$RECAPTCHA_SECRET" ]; then
          echo "❌ RECAPTCHA_SECRET_KEY is empty or not set in environment"
          exit 1
        else
          echo "✅ RECAPTCHA_SECRET_KEY is available (${#RECAPTCHA_SECRET} characters)"
        fi
        
        # Use PHP for reliable string replacement
        php -r "
          \$config = file_get_contents('api/config.php');
          \$config = str_replace('YOUR_SECRET_KEY_HERE', getenv('RECAPTCHA_SECRET'), \$config);
          file_put_contents('api/config.php', \$config);
        "
        
        # Verify the replacement worked
        if grep -q "YOUR_SECRET_KEY_HERE" api/config.php; then
          echo "❌ Secret key replacement failed - placeholder still exists"
          exit 1
        else
          echo "✅ Secret key configured successfully"
        fi
      
    - name: Deploy Backend to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: './api/'
        server-dir: ${{ secrets.BACKEND_DEPLOY_PATH || format('{0}/api/', secrets.DEPLOY_PATH) }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/README.md
          **/test-*.sh
          
    - name: Cleanup temporary files
      run: |
        # Remove backup file if it exists
        rm -f api/config.php.backup
        echo "🧹 Cleaned up temporary files"
          
    - name: Backend deployment notification
      run: |
        echo "✅ Backend successfully deployed to ${{ env.ENVIRONMENT_NAME }} environment"
        echo "📁 Deployed to: ${{ secrets.BACKEND_DEPLOY_PATH || format('{0}/api/', secrets.DEPLOY_PATH) }}"
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "🚀 Manual deployment triggered"
          echo "📋 Branch: ${{ github.event.inputs.branch }}"
          echo "🎯 Environment: ${{ github.event.inputs.environment }}"
        fi
